Quest completed
KamilProgram/html-hometask-KamilProgram-2 pull request #1
Opened 2021-06-03 18:10 UTC by KamilProgram

2021-06-04 00:06 UTC, Roman-Maksimov requested changes

2021-06-04 00:06 UTC, Roman-Maksimov commented on scss/style.scss
> +        flex: 0 1 16.666%;
Пусть останется 16%, но вообще по макету требовалось 220px, дизайнер с большой долей вероятности придрался бы.

2021-06-04 00:06 UTC, Roman-Maksimov commented on scss/style.scss
> +            border-radius: 10px;
Полагаю, префиксы просто для практики? Ибо препроцессоры умеют их добавлять.

2021-06-04 00:06 UTC, Roman-Maksimov commented on scss/style.scss
> +            margin: 0 #{"-" + $wrapperSidePadding} 16px #{"-" + $wrapperSidePadding};
Вроде бы можно просто
```scss
margin: 0 -$wrapperSidePadding 16px;
```

2021-06-04 00:06 UTC, Roman-Maksimov commented on scss/style.scss
> +                    background-color: #e99330;
тень забыли

2021-06-04 00:37 UTC, Roman-Maksimov requested changes

2021-06-04 00:37 UTC, Roman-Maksimov commented on scss/style.scss
> +            margin: 0;
К чему лишний margin?

2021-06-04 07:34 UTC, KamilProgram commented on detailed-page.html
> +                <input type="text" placeholder="Search products">
Я как раз хотел спросить на сколько это может быть критично, потому что Emmet в VS Code одиночные тэги не закрывает

2021-06-04 07:49 UTC, KamilProgram commented on scss/style.scss
> +        flex: 0 1 16.666%;
Вот тут я немного запутался потому что по макету отступы сбоку страницы везде одинаковые 24px, а контент отцентрован. То есть если поставить ширину 220px то при сужении появятся дополнительные отступы сбоку, к чему дизайнер тоже можно придраться)

2021-06-04 08:03 UTC, KamilProgram commented on scss/style.scss
> +            margin: 0 #{"-" + $wrapperSidePadding} 16px #{"-" + $wrapperSidePadding};
Точно, я даже не пробовал😅

2021-06-04 08:05 UTC, KamilProgram commented on scss/style.scss
> +            border-radius: 10px;
Я использовал плагин Live Sass Compiler, он префиксы для border-radius не ставит. Что так же как и с закрывающими тэгами в emmet немного не понятно

2021-06-04 08:07 UTC, KamilProgram commented on scss/style.scss
> +    max-width: 1440px;
Хорошо

2021-06-04 08:45 UTC, KamilProgram commented on scss/style.scss
> +            margin: 0;
Ни к чему, уже исправил😅

2021-06-04 14:56 UTC, Roman-Maksimov commented on detailed-page.html
> +                <input type="text" placeholder="Search products">
На работоспособность это не виляет. Возможно, в дальнейшем в не будет их закрывать (зависит от команды, в которой вы будете работать). Но, раз уж мы практикуемся, пока на такие вещи я буду обращать ваше внимание.

2021-06-04 15:00 UTC, Roman-Maksimov commented on scss/style.scss
> +        flex: 0 1 16.666%;
Это можно решить не центрированием, а space-between. Если есть конфликт постановки, тогда вопрос можно адресовать дизайнеру, чтобы он решил, что растягивать, карточки или отступы между ними

2021-06-04 15:02 UTC, Roman-Maksimov commented on scss/style.scss
> +            margin: 0 #{"-" + $wrapperSidePadding} 16px #{"-" + $wrapperSidePadding};
тогда попробуйте `margin: 0 -1*$wrapperSidePadding 16px;`, но вообще странно, обычно препроцессоры это нормально переваривают

2021-06-05 07:57 UTC, KamilProgram commented on scss/style.scss
> +            margin: 0 #{"-" + $wrapperSidePadding} 16px #{"-" + $wrapperSidePadding};
А всё понял, препроцессор парсит конструкцию `0 -$value` как выражение  `0 - value`. То есть умножение на `-1` работает потому что после минуса нет `$`

margin: 0 #{"-" + $wrapperSidePadding} 16px #{"-" + $wrapperSidePadding}; --> margin: 0 -24px 16px -24px;
margin: 0 -$wrapperSidePadding 16px -$wrapperSidePadding; -->  margin: -24px -8px;
margin: 0 -$wrapperSidePadding 16px; -->margin: -24px 16px;
margin: 0 -1 * $wrapperSidePadding 16px; -->margin: 0 -24px 16px;

2021-06-05 11:32 UTC, KamilProgram commented on scss/style.scss
> +        flex: 0 1 16.666%;
Но если поставить space-between то карточки в последней строке не будут отцентрованы, а займут ширину всей строки.
Поставил поставил 220px, а для экранов меньше 1447px оставил в процентах

2021-06-08 11:08 UTC, Roman-Maksimov commented on scss/style.scss
> +            margin: 0 #{"-" + $wrapperSidePadding} 16px #{"-" + $wrapperSidePadding};
Тогда можно просто в скобки взять `margin: 0 (-$wrapperSidePadding) 16px;`

2021-06-08 11:49 UTC, Roman-Maksimov approved these changes

2021-06-08 11:50 UTC, closed without merging